# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.
wrapperVersion=3.3.2
distributionUrl=https://dlcdn.apache.org/maven/maven-3/3.9.7/binaries/apache-maven-3.9.7-bin.zip
distributionSha512Sum=c74a71fc9b7b37b7a0bf7734f0bc2de6cdcdf528108d42c4ccbd16d6bb57a0ad7a356c8e61d784196c8acf1ab7a6de452de174eaf1bef3349fb645bcddd67dd9
